##项目附加信息
app:
  author: wudskq

##web端口等配置
server:
  port: 8099

spring:
  profiles:
    active: prod
  mvc:
    hiddenmethod:
      filter:
        enabled: true  # [fix]stream closed

# mybatis-plus
mybatis-plus:
    typeAliasesPackage: cn.com.wudskq.model
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    configuration:
      # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
      #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      # 返回类型为Map,显示null对应的字段
      call-setters-on-nulls: true

# JWT配置
jwt:
  # 密匙Key
  secret: AXzYB2^y2$&#1!#&5h
  # HeaderKey
  tokenHeader: Authorization
  # Token前缀
  tokenPrefix: Bearer
  # 过期时间，单位秒
  expiration: 86400
  # 配置白名单（不需要认证）
  antMatchers: /swagger-resources/**,/swagger-ui.html,/v2/api-docs,/webjars/**,/doc.html,/druid/**


## xxl-job
xxl:
  job:
    accessToken:
    admin:
      addresses: http://101.42.156.134:8082/xxl-job-admin
    executor:
      address:
      appname: wc-manager-system
      ip:
      logpath: ./logs/xxl-job/jobhandler
      logretentiondays: 30
      port: 7688

