##项目附加信息
app:
  author: wudskq

##web端口等配置
server:
  port: 8099

spring:
  profiles:
    active: dev


##mybatis-puls
mybatis-plus:
  configuration:
    typeAliasesPackage: cn.com.wudskq.model


# JWT配置
jwt:
  # 密匙Key
  secret: AXzYB2^y2$&#1!#&5h
  # HeaderKey
  tokenHeader: Authorization
  # Token前缀
  tokenPrefix: Bearer
  # 过期时间，单位秒
  expiration: 86400
  # 配置白名单（不需要认证）
  antMatchers: /swagger-resources/**,/swagger-ui.html,/v2/api-docs,/webjars/**,/doc.html,/druid/**



